CREATE OR REPLACE TABLE BREW_PROFILE (
 PROFILE_ID INT NOT NULL AUTO_INCREMENT,
 PROFILE_NAME VARCHAR(255) NOT NULL,
 STAGE_ID INT NOT NULL,
 STAGE_NAME VARCHAR(255) NOT NULL,
 START_TIME TIME NOT NULL,
 FINISH_TIME TIME NOT NULL,
 MIN_TEMP DOUBLE NOT NULL,
 MAX_TEMP DOUBLE NOT NULL,
 ALERT_ON_FINISH BOOLEAN NOT NULL,
 PRIMARY KEY(PROFILE_ID, STAGE_ID)
)


CREATE OR REPLACE TABLE MEASURESMENTS (
 ID INT NOT NULL AUTO_INCREMENT,
 PROFILE VARCHAR(255) NOT NULL,
 DATE DATETIME NOT NULL,
 FERMENTER_TEMP DOUBLE NOT NULL,
 WITHIN_TEMP_RANGE BOOLEAN NOT NULL,
 AMBIENT_TEMP DOUBLE DEFAULT 0.0,
 HEATER_ON BOOLEAN NOT NULL,
 COOLING_ON BOOLEAN NOT NULL,
 PRIMARY KEY(ID)
);


INSERT INTO BREW_PROFILE (PROFILE_ID, PROFILE_NAME, STAGE_ID, STAGE_NAME, START_TIME, FINISH_TIME, ALERT_ON_FINISH)
VAULES
(1, 'COOPERS IPA', 1, 'FERMENTATION', '0 00:00:00', '3 00:00:00', 20.0, 21.5, TRUE);
